### PR TITLE
Update to 1.19.4

### PR DESCRIPTION
**Pull request by unilock**
- Update dependencies
- Update mixin
- Rename "fabric" to "fabric-api" in `fabric.mod.json` (recent change Fabric-side)
- Add "minVersion" to mixin config (gets rid of the trivial "Mixin ... does not specify "minVersion" property" error in log during startup)

### CODE REVIEW

**Comment by HhiPyrene** [comment]
Got crash
[crash-2023-04-01_00.32.57-client.txt](https://github.com/TeamMidnightDust/SwordBlocking/files/11124070/crash-2023-04-01_00.32.57-client.txt)

**Comment by HhiPyrene** [comment]
Got crash
[crash-2023-04-01_00.32.57-client.txt](https://github.com/TeamMidnightDust/SwordBlocking/files/11124070/crash-2023-04-01_00.32.57-client.txt)

**Comment by unilock** [comment]
@HhiPyrene I can't reproduce with the set of mods in your crash log :(

Although, I may not have the *exact* same set of mods, since some of them weren't available via CurseForge nor Modrinth... (i.e. GitHub Actions)

Would you be able to archive your `config` + `mods` folders in a ZIP or what have you, and share a link to it here? (hopefully the legality of that isn't questionable enough to get me in trouble)

**Comment by HhiPyrene** [comment]
[latest.log](https://github.com/TeamMidnightDust/SwordBlocking/files/11182526/latest.log)
[crash-2023-04-08_12.35.00-client.txt](https://github.com/TeamMidnightDust/SwordBlocking/files/11182527/crash-2023-04-08_12.35.00-client.txt)
Though the other mods disabled, it still crashed. Maybe it broke QUILT, which seems a trouble.

**Comment by unilock** [comment]
@HhiPyrene I still can't reproduce, even with your exact setup :(

Minecraft: `1.19.4`
Quilt: `0.19.0-beta.2`
QFAPI / QSL: `QFAPI 6.0.0-beta.2 + QSL 5.0.0-beta.1`
SwordBlocking: `1.3.0` (my fork)

I'll try changing the `InGameHud` mixin from a `@Redirect` to an `@Inject`; maybe that'll fix it?

**Comment by HhiPyrene** [comment]
I know why. Gradle 8.0 made the build broken, confusing us. I tried to use Gradle 7.5.1 to build again and it worked fine. 
:\
[build.zip](https://github.com/TeamMidnightDust/SwordBlocking/files/11183670/build.zip)

**Comment by HhiPyrene** [comment]
> I know why. Gradle 8.0 made the build broken, confusing us. I tried to use Gradle 7.5.1 to build again and it worked fine. 
> :/
>My mistake. [build.zip](https://github.com/TeamMidnightDust/SwordBlocking/files/11183670/build.zip)
>

**Comment by Motschen** [comment]
Thank you very much :)

**Pull request merged**
